- name: 1-2001-01_install_bind - install package
  yum:
    name: {{ item.name }}
    state: present
  with_items: bind_bind.packages | default("")

- name: 1-2001-01_install_bind - enable services
  service:
    name: {{ item.name }}
    state: {{ item.state }}
    enabled: {{ item.enabled }}
  with_items:
    - { name: named, enabled: no, state: stopped}
    - { name: named-chroot, enabled: yes, state: started}

- name: 1-2001-01_install_bind - configure firewalld
  firewalld:
    service: dns
    permanent: true
    state: enabled
