---
- name: 1-2001-02_configure_bind - setting files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: yes
  with_items:
    - { src: "{{ bind_bind.conftempl }}", dest: "{{ bind_bind.confdir }}/{{ bind_bind.conffile }}", owner: "{{ bind_bind.confowner }}", group: "{{ bind_bind.confgroup }}", mode: "{{ bind_bind.confmode }}"}
    - { src: "{{ bind_bind.zonetempl }}", dest: "{{ bind_bind.zonedir }}/{{ bind_bind.zonefile }}", owner: "{{ bind_bind.zoneowner }}", group: "{{ bind_bind.zonegroup }}", mode: "{{ bind_bind.zonemode }}"}
    - { src: "{{ bind_bind.revtempl }}", dest: "{{ bind_bind.zonedir }}/{{ bind_bind.revfile }}", owner: "{{ bind_bind.zoneowner }}", group: "{{ bind_bind.zonegroup }}", mode: "{{ bind_bind.zonemode }}"}
  notify:
    - start_named-chroot
