bind:
  packs:                                                        # インストールするパッケージ
    - name: bind.x86_64
    - name: "bind-chroot.x86_64"
    - name: "bind-libs.x86_64"
    - name: "bind-utils.x86_64"
  conftempl: named.conf.j2
  conffile: named.conf
  confdir: /etc
  confowner: root
  confgroup: named
  confmode: 755
  zonetempl: stone.zone.j2
  zonefile: stone.zone
  zonedir: /var/named
  zoneowner: root
  zonegroup: named
  zonemode: 755
  revtempl: stone.rev.j2
  revfile: stone.rev
  acl_name: stone-network
  acl_segments:
    - { network: 192.168.3.0/24 }
    - { network: 192.168.10.0/24 }


